dist: bionic

os: linux

language: cpp

compiler: gcc

script:
  - bash platform-scripts/linux/build.sh -t --coverage
  - bash platform-scripts/linux/build.sh -r -t --coverage
  - bash platform-scripts/linux/test.sh --coverage
