name: CMake

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Debug
      run: bash build.sh -t

    - name: Build Release
      run: bash build.sh -r -t
    
    - name: Test
      run: bash test.sh -c
      
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_coverage.xml
        retention-days: 5
