name: CMake

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: sudo apt-get install gcovr -y

      - name: Build Debug
        run: bash build.sh -t

      - name: Build Release
        run: bash build.sh -r -t

      - name: Test
        run: bash test.sh -c

      - name: Upload test results and coverage
        uses: actions/upload-artifact@v2
        with:
          name: test-results-coverage
          path: |
            test_results.xml
            moon_coverage_html/
            moon_coverage.xml
          retention-days: 5
