name: linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: sudo apt-get install gcovr -y

      - name: Build Debug
        run: bash platform-scripts/linux/build.sh -t --coverage

      - name: Build Release
        run: bash platform-scripts/linux/build.sh -r -t --coverage

      - name: Test
        run: bash platform-scripts/linux/test.sh --coverage

      - name: Upload test results and coverage
        uses: actions/upload-artifact@v2
        with:
          name: test-results-coverage
          path: |
            test_results.xml
            moon_coverage.html
            moon_coverage.xml
          retention-days: 5

      - name: Upload code coverage to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash) -f moon_coverage.xml
