name: windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Debug
        run: platform-scripts\windows\build -t

      - name: Test Debug
        run: platform-scripts\windows\test

      - name: Build Release
        run: platform-scripts\windows\build -r -t

      - name: Test Release
        run: platform-scripts\windows\test -r
