name: windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        args: [ -d -t, -d -t --shared, -r -t, -r -t --shared ]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: platform-scripts\windows\build ${{ matrix.args }}
      - name: Test
        run: platform-scripts\windows\test ${{ matrix.args }}

  mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        args: [ -r -t --mingw, -r -t --shared --mingw ]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: platform-scripts\windows\build ${{ matrix.args }}
      - name: Test
        run: platform-scripts\windows\test ${{ matrix.args }}
